apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
  annotations:
    team: data-insights 
    source-code: https://github.com/Gnomon-iterative/cloud-cost
  # Testing workflow trigger with pull_request_target
