name: Team Validator

on:
  pull_request:
    branches:
      - main
    paths:
      - 'namespaces/**'

# Add permissions block to allow commenting on PRs
permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate Team Membership
        uses: Gnomon-iterative/github-team-validator@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          organization: Gnomon-iterative
