name: Team Validator

on:
  pull_request:
    branches:
      - main
    paths:
      - 'namespaces/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Team Validator
        uses: Gnomon-iterative/github-team-validator@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr-number: ${{ github.event.pull_request.number }}
          organization: 'Gnomon-iterative'
